apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postegres:13.13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: pg1234
            - name: POSTGRES_USER
              value: kubenews
            - name: POSTGRES_DB
              value: kubenews
